; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+8
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


